# Generated by Django 5.1.5 on 2025-02-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('emailAddress', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('regesiter_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
